[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aer-search-aws-goes-workspace"
version = "1.0.0"
description = "A plugin repository for the AWS GOES aer search component"
readme = "README.md"
requires-python = ">=3.13"
license = "Apache-2.0"
authors = [{ name = "Fran Dorr" }]
dependencies = [
    "aer-eo",
    "geopandas>=1.1.2",
    "pandera[geopandas]>=0.24.0",
    "s3fs>=2026.2.0",
]

[tool.uv]
managed = true

[tool.uv.sources]
aer-eo = { path = "../aer/projects/aer-core", editable = true }

[tool.uv.workspace]
members = ["projects/*"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
dev-mode-dirs = ["components", "bases", "development", "."]

[tool.ruff]
exclude = [
    ".git",
    ".github",
    "__pycache__",
    ".ruff_cache",
    "dist",
    ".venv",
    "./development/*.py",
]
line-length = 120

[tool.basedpyright]
venvPath = "."
venv = ".venv"
extraPaths = ["components/", "bases/"]

[dependency-groups]
dev = [
    "majortom-eg>=1.0.0,<2.0.0",
    "marimo[mcp]>=0.21.1,<0.22.0",
    "polylith-cli>=1.43.0,<2.0.0",
    "pytest>=9.0.2,<10.0.0",
    "python-semantic-release>=10.5.3,<11.0.0",
]

[tool.polylith]
bricks."components/aer/search-aws-goes" = "aer/search-aws-goes"

[tool.pytest.ini_options]
markers = [
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
